const CONFIG = {
    titleWeb: "NhanHoiDap",
    introTitle: ' Thịnh Chó Đỏ',
    introDesc: '` Bây giờ Nhân hỏi Thịnh trả lời ok chưa`',
    btnIntro: '^^Ok Nhân^^',
    title: 'Thịnh thấy Nhân đẹp trai không🥰',
    desc: 'Trả lời thật lòng nha Ku',
    btnYes: 'Nhân đẹp trai lắm,còn vui tính <33',
    btnNo: 'Không nha :((',
    question: 'Trên thế giới hơn 7 tỉ người mà sao Thịnh lại yêu Thơ <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Thịnh có yêu Thơ đâu😜 Thịnh đang bứ nên mới yêu Thơ <33333333',
    mess: 'Nhân biết mà 😏. Thịnh tha cho con gái nhà người ta đi  😞😞',
    messDesc: 'Nhân khuyên Thịnh nên chơi bê đê đi,Nhân biết Thịnh là người chơi nhiều hệ mà .',
    btnAccept: 'Ok luôn Thịnh sẽ chơi Bê Đê <3',
    messLink: 'https://github.com/zukahai/Confess-Crush' //link mess của các bạn. VD: https://m.me/nam.nodemy
